#!/usr/bin/env python3
"""
Build the manifest.json for the cognitive-linguistics-canon project.

Reads the Osaka archive scrape output, cross-references against existing
catalog entries, assigns frames and categories, and adds primary metaphors
from Grady/Lakoff-Johnson that are not in the Osaka archive.

Usage:
    python scrape_osaka_archive.py | python build_manifest.py > manifest.json
"""

import json
import sys

# Existing mapping slugs in the catalog (as of 2026-03-11).
# These are excluded from the candidate list to avoid duplicates.
EXISTING_SLUGS = {
    "action-is-motion",
    "activities-are-containers",
    "argument-is-war",
    "argument-is-a-building",
    "argument-is-a-journey",
    "argument-is-dance",
    "causes-are-forces",
    "change-is-motion",
    "communication-is-sending",
    "conscious-is-up",
    "creative-process-is-construction",
    "creative-process-is-gardening",
    "difficulties-are-impediments-to-motion",
    "emotional-stability-is-balance",
    "emotions-are-entities-within-a-person",
    "existence-is-a-location",
    "finished-is-up",
    "foreseeable-future-is-up",
    "good-is-up",
    "happy-is-up",
    "having-control-is-up",
    "health-is-up",
    "ideas-are-commodities",
    "ideas-are-cutting-instruments",
    "ideas-are-fashions",
    "ideas-are-food",
    "ideas-are-light-sources",
    "ideas-are-money",
    "ideas-are-objects",
    "ideas-are-people",
    "ideas-are-plants",
    "ideas-are-products",
    "ideas-are-resources",
    "inflation-is-an-entity",
    "labor-is-a-resource",
    "life-is-a-container",
    "life-is-a-gambling-game",
    "life-is-a-journey",
    "longterm-purposeful-change-is-a-journey",
    "love-is-a-collaborative-work-of-art",
    "love-is-a-journey",
    "love-is-a-patient",
    "love-is-a-physical-force",
    "love-is-a-unity",
    "love-is-madness",
    "love-is-war",
    "more-is-up",
    "obligations-are-forces",
    "people-are-machines",
    "problems-are-puzzles",
    "properties-are-possessions",
    "psychological-forces-are-physical-forces",
    "purposes-are-destinations",
    "rational-is-up",
    "seeing-is-touching",
    "significant-is-big",
    "states-are-locations",
    "status-is-up",
    "the-conduit-metaphor",
    "the-mind-is-a-brittle-object",
    "the-mind-is-a-machine",
    "the-visual-field-is-a-bounded-region",
    "the-visual-field-is-a-container",
    "theories-are-buildings",
    "time-is-a-limited-resource",
    "time-is-a-moving-object",
    "time-is-money",
    "time-is-stationary-and-we-move-through-it",
    "understanding-is-seeing",
    "unknown-is-up",
    "virtue-is-up",
    "an-instrument-is-a-companion",
    "a-place-to-wait",
    "unknown-is-up",
}

# Existing frames in the catalog for mapping.
EXISTING_FRAMES = {
    "animal-husbandry", "architecture-and-building", "argumentation",
    "cartography", "causal-reasoning", "collaborative-work", "communication",
    "competition", "computing", "containers", "creative-process", "dance",
    "data-processing", "economics", "embodied-experience", "event-structure",
    "fluid-dynamics", "folk-taxonomy", "food-and-cooking", "gambling",
    "governance", "hardware-compatibility", "horticulture",
    "intellectual-inquiry", "journeys", "library-and-archive", "life-course",
    "love-and-relationships", "manufacturing", "mediation", "medicine",
    "mental-experience", "military-command", "mythology", "natural-phenomena",
    "natural-selection", "network-security", "object-oriented-design",
    "organizational-behavior", "physics", "publishing", "puzzles-and-games",
    "religion", "representation", "shared-resources", "social-behavior",
    "social-roles", "software-abstraction", "software-programs",
    "surveillance", "systems-performance", "time-and-temporality", "tool-use",
    "travel", "vision", "war",
}

# Frame mapping: map source/target stubs to existing or new frames.
# This maps common terms appearing in Osaka metaphor names to frame slugs.
FRAME_MAP = {
    # Source domains (what provides the metaphorical structure)
    "warmth": "embodied-experience",
    "heat": "embodied-experience",
    "cold": "embodied-experience",
    "motion": "embodied-experience",
    "self-propelled motion": "embodied-experience",
    "up": "embodied-experience",
    "balance": "embodied-experience",
    "physical closeness": "embodied-experience",
    "physical forces": "physics",
    "physical properties": "embodied-experience",
    "physical injury": "embodied-experience",
    "contact with physical self": "embodied-experience",
    "contact with the ground": "embodied-experience",
    "maintaining position": "embodied-experience",
    "lowering": "embodied-experience",
    "blinding": "embodied-experience",
    "nausea": "embodied-experience",
    "a body": "embodied-experience",
    "body of water": "fluid-dynamics",
    "a fluid": "fluid-dynamics",
    "a liquid": "fluid-dynamics",
    "a substance": "fluid-dynamics",
    "a substance contained in affecting causes": "physics",
    "a substance directed at an affected party": "physics",
    "a moving object": "physics",
    "a line": "physics",
    "gravity": "physics",
    "forces": "physics",
    "forces affecting": "physics",
    "forces between the desired and the desirer": "physics",
    "a journey": "journeys",
    "paths": "journeys",
    "open paths": "journeys",
    "path over which motion occurs": "journeys",
    "forward motion": "journeys",
    "a landscape we move through": "journeys",
    "a region in a landscape": "journeys",
    "locations": "journeys",
    "a location (here)": "journeys",
    "relative location": "journeys",
    "change of direction": "journeys",
    "a race": "competition",
    "war": "war",
    "1 on 1 physical aggression": "competition",
    "competition for desired objects": "competition",
    "fighting a war": "war",
    "an offensive weapon": "war",
    "weapons": "war",
    "adversaries": "war",
    "food": "food-and-cooking",
    "eating": "food-and-cooking",
    "hunger": "food-and-cooking",
    "ingesting a substance compulsively": "food-and-cooking",
    "a container": "containers",
    "a container (here)": "containers",
    "containers": "containers",
    "a locked container for its solution": "containers",
    "containers for money": "containers",
    "a bounded region": "containers",
    "a solid": "containers",
    "a cover": "containers",
    "covers for the facts": "containers",
    "contents": "containers",
    "shapes": "containers",
    "an object": "containers",
    "objects": "containers",
    "linked objects": "containers",
    "entities": "containers",
    "entities inside a person": "containers",
    "entities within a person": "containers",
    "possessions": "economics",
    "a resource": "economics",
    "resources": "economics",
    "money": "economics",
    "wealth": "economics",
    "commercial transaction": "economics",
    "a benefical possession": "economics",
    "inflation": "economics",
    "shopping": "economics",
    "giving an object": "economics",
    "control over possessions": "economics",
    "control over an object relative to a possessor": "economics",
    "control over an entity relative to a location": "governance",
    "control over relative location": "governance",
    "making": "manufacturing",
    "making visible": "manufacturing",
    "moving to a location (here)": "manufacturing",
    "constructed objects": "architecture-and-building",
    "a constructed object": "architecture-and-building",
    "a machine": "manufacturing",
    "an activated machine": "manufacturing",
    "cultivation": "horticulture",
    "plants": "horticulture",
    "alive": "life-course",
    "life": "life-course",
    "beings with a life cycle": "life-course",
    "beings with life cycles": "life-course",
    "birthing": "life-course",
    "a child": "life-course",
    "children (w.r.t development)": "life-course",
    "an animal": "animal-husbandry",
    "kinship": "social-roles",
    "people": "social-roles",
    "people (w.r.t. family tree structure)": "social-roles",
    "people (w.r.t. opinions)": "social-roles",
    "distinct individuals": "social-roles",
    "a body": "embodied-experience",
    "light": "vision",
    "a light source": "vision",
    "light sources": "vision",
    "visibility": "vision",
    "reception": "vision",
    "shape recognition": "vision",
    "touching, eyes are limbs": "vision",
    "adherence": "embodied-experience",
    "following": "journeys",
    "tightness": "embodied-experience",
    "fashions": "economics",
    "guides": "journeys",
    "love objects": "love-and-relationships",
    "a unity (of two complementary parts)": "love-and-relationships",
    "a possession": "economics",
    "magic": "mythology",
    "madness": "mental-experience",
    "material": "manufacturing",
    "cloth": "manufacturing",
    "contagious diseases": "medicine",
    "musical harmony": "creative-process",
    "becoming electrified": "physics",
    "getting a burden": "embodied-experience",
    "getting destroyed": "war",
    "linguistic communication": "communication",
    "writing": "communication",
    "temporal precedence": "time-and-temporality",
    "a changer": "time-and-temporality",
    "a container (bounded)": "containers",
    "a pursuer": "time-and-temporality",
    "something moving toward you": "time-and-temporality",
    "holding": "embodied-experience",
    "transferring an object": "embodied-experience",
    "causal relations": "causal-reasoning",
    "replacement": "manufacturing",
    "aligned": "embodied-experience",
    "whole": "embodied-experience",
    "a target": "war",
    "a tangle": "embodied-experience",
    "batteries": "physics",
    "solving a puzzle": "puzzles-and-games",
    "climate": "natural-phenomena",
    "change": "event-structure",
    "perceptions": "vision",
    "straightness": "embodied-experience",
    "cleanliness": "embodied-experience",
    "purity": "embodied-experience",
    "an external event exerting force on": "physics",
    "injuries": "embodied-experience",
    "having a harmful possession": "economics",
    "lacking a needed possession": "economics",
    "causing functional objects to be nonfunctional": "manufacturing",
    "being in a harmful location": "journeys",
    "preventing forward motion toward a goal": "journeys",
    "comparison of physical properties": "embodied-experience",
    "comparison of possessions (non-evaluative)": "economics",
}

# Target domain frame mappings
TARGET_FRAME_MAP = {
    "a force": "physics",
    "a problem": "causal-reasoning",
    "a schedule": "time-and-temporality",
    "abilities": "mental-experience",
    "acting compulsively": "mental-experience",
    "acting on": "event-structure",
    "action": "event-structure",
    "active": "event-structure",
    "affection": "love-and-relationships",
    "anger": "mental-experience",
    "aspects of the self": "mental-experience",
    "attributes": "event-structure",
    "beliefs": "mental-experience",
    "causal precedence": "causal-reasoning",
    "causation": "causal-reasoning",
    "causes and effects": "causal-reasoning",
    "change": "event-structure",
    "change of state": "event-structure",
    "coherent": "intellectual-inquiry",
    "communication": "communication",
    "comparing and seeking": "economics",
    "comparison of properties": "intellectual-inquiry",
    "competition": "competition",
    "complience": "governance",
    "conceit": "mental-experience",
    "conducting research": "intellectual-inquiry",
    "control": "governance",
    "creating": "creative-process",
    "creation": "creative-process",
    "dangerous beliefs": "mental-experience",
    "darkness": "natural-phenomena",
    "desire": "mental-experience",
    "desires": "mental-experience",
    "difficult subjects": "intellectual-inquiry",
    "difficulties": "event-structure",
    "difficulty": "event-structure",
    "disgust": "mental-experience",
    "disparity": "intellectual-inquiry",
    "effect on emotional self": "mental-experience",
    "effects of humor": "mental-experience",
    "emotion": "mental-experience",
    "emotional intimacy": "love-and-relationships",
    "emotional self": "mental-experience",
    "emotional stability": "mental-experience",
    "emotions": "mental-experience",
    "euphoric states": "mental-experience",
    "event structure": "event-structure",
    "existence": "event-structure",
    "external appearance": "vision",
    "external conditions": "event-structure",
    "external events affecting progress": "event-structure",
    "facts": "intellectual-inquiry",
    "fear": "mental-experience",
    "force": "physics",
    "form": "event-structure",
    "gaining physical intimacy (against resistance)": "love-and-relationships",
    "getting": "event-structure",
    "harm": "event-structure",
    "harming": "event-structure",
    "hope": "mental-experience",
    "ideas": "intellectual-inquiry",
    "intelligence": "mental-experience",
    "intense emotions": "mental-experience",
    "interaction between progress and external events affecting": "event-structure",
    "interpersonal harmony": "social-behavior",
    "intoxication": "mental-experience",
    "investments": "economics",
    "knowledge of past events": "mental-experience",
    "laughter": "mental-experience",
    "light": "natural-phenomena",
    "linear scales": "intellectual-inquiry",
    "logic": "intellectual-inquiry",
    "logical relations": "intellectual-inquiry",
    "longterm purposeful activity": "event-structure",
    "longterm purposeful change": "event-structure",
    "love": "love-and-relationships",
    "loved one": "love-and-relationships",
    "lust": "love-and-relationships",
    "lustful person": "love-and-relationships",
    "machines": "manufacturing",
    "means of change": "event-structure",
    "mental accounting": "economics",
    "mind, or mental self": "mental-experience",
    "mind": "mental-experience",
    "money": "economics",
    "moral accounting": "ethics-and-morality",
    "morality": "ethics-and-morality",
    "necessary prerequisite for change": "event-structure",
    "obligations": "governance",
    "opportunities": "event-structure",
    "people": "social-roles",
    "perception": "vision",
    "personality": "mental-experience",
    "possessing": "economics",
    "problem": "causal-reasoning",
    "properties": "event-structure",
    "psychological forces": "mental-experience",
    "rational": "mental-experience",
    "receiving serious thought": "mental-experience",
    "relationship": "social-roles",
    "responsibilities": "governance",
    "seeing": "vision",
    "self-initiated change of state": "event-structure",
    "sexuality": "love-and-relationships",
    "shapes": "containers",
    "social accounting": "social-behavior",
    "society": "social-roles",
    "states": "event-structure",
    "strong emotion": "mental-experience",
    "strong emotions": "mental-experience",
    "subjects": "intellectual-inquiry",
    "the body": "embodied-experience",
    "the conduit metaphor": "communication",
    "the event structure metaphorical system": "event-structure",
    "the mind": "mental-experience",
    "the progress of external events": "event-structure",
    "the visual field": "vision",
    "theoretical debate": "intellectual-inquiry",
    "theories": "intellectual-inquiry",
    "time": "time-and-temporality",
    "treating illness": "medicine",
    "well-being": "mental-experience",
    "words": "communication",
}

# Additional primary metaphors from Grady (1997) and Lakoff & Johnson
# (1999) not in the Osaka archive.
ADDITIONAL_PRIMARY_METAPHORS = [
    {
        "slug": "knowing-is-seeing",
        "name": "KNOWING IS SEEING",
        "kind": "primary-metaphor",
        "source_frame": "vision",
        "target_frame": "mental-experience",
        "categories": ["cognitive-science", "linguistics", "philosophy"],
        "source": "llm",
        "archive_ref": "Grady 1997; Lakoff & Johnson 1999 pp. 53-54; Sweetser 1990",
        "description": "The foundational epistemic metaphor. We 'see' what someone means, have 'insight', and seek 'illumination'. Grady identifies this as a primary metaphor grounded in the correlation between visual perception and knowledge acquisition in infancy. Sweetser (1990) traces it across Indo-European languages.",
    },
    {
        "slug": "understanding-is-grasping",
        "name": "UNDERSTANDING IS GRASPING",
        "kind": "primary-metaphor",
        "source_frame": "embodied-experience",
        "target_frame": "mental-experience",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Grady 1997; Lakoff & Johnson 1999 pp. 54",
        "description": "We 'grasp' concepts, 'get a hold of' ideas, find some things 'hard to get'. The correlation of manual manipulation with cognitive comprehension in early development grounds this primary metaphor.",
    },
    {
        "slug": "categories-are-containers",
        "name": "CATEGORIES ARE CONTAINERS",
        "kind": "primary-metaphor",
        "source_frame": "containers",
        "target_frame": "intellectual-inquiry",
        "categories": ["cognitive-science", "linguistics", "philosophy"],
        "source": "llm",
        "archive_ref": "Lakoff & Johnson 1999 pp. 52; Lakoff 1987 Ch 6",
        "description": "Things are 'in' or 'out of' categories. Category membership is containment. This primary metaphor structures all classification and set theory. It follows from the container image schema applied to conceptual grouping.",
    },
    {
        "slug": "similarity-is-closeness",
        "name": "SIMILARITY IS CLOSENESS",
        "kind": "primary-metaphor",
        "source_frame": "embodied-experience",
        "target_frame": "intellectual-inquiry",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Grady 1997; Lakoff & Johnson 1999 pp. 50",
        "description": "Similar things are 'close' to each other, differences are 'distances'. This primary metaphor underlies all spatial models of similarity (e.g., multidimensional scaling, semantic spaces).",
    },
    {
        "slug": "organization-is-physical-structure",
        "name": "ORGANIZATION IS PHYSICAL STRUCTURE",
        "kind": "primary-metaphor",
        "source_frame": "architecture-and-building",
        "target_frame": "event-structure",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Lakoff & Johnson 1999 pp. 52",
        "description": "Abstract organization is understood through physical spatial structure. An argument has 'structure', a theory has 'foundations', an organization has 'levels'.",
    },
    {
        "slug": "help-is-support",
        "name": "HELP IS SUPPORT",
        "kind": "primary-metaphor",
        "source_frame": "embodied-experience",
        "target_frame": "social-behavior",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Grady 1997; Lakoff & Johnson 1999 pp. 52",
        "description": "To help someone is to 'support' them, to 'prop them up', to be their 'pillar'. The embodied correlation: holding something up prevents it from falling.",
    },
    {
        "slug": "importance-is-size",
        "name": "IMPORTANCE IS SIZE",
        "kind": "primary-metaphor",
        "source_frame": "embodied-experience",
        "target_frame": "event-structure",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Grady 1997; Lakoff & Johnson 1999 pp. 50",
        "description": "Important things are 'big', trivial things are 'small'. A 'big' day, a 'small' matter. The embodied grounding: large things in the visual field demand more attention.",
    },
    {
        "slug": "bad-is-stinky",
        "name": "BAD IS STINKY",
        "kind": "primary-metaphor",
        "source_frame": "embodied-experience",
        "target_frame": "mental-experience",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Lakoff & Johnson 1999 pp. 51",
        "description": "Bad things 'stink', are 'rotten', 'smell fishy'. The correlation of olfactory disgust with negative evaluation is one of the most basic embodied judgments.",
    },
    {
        "slug": "intimacy-is-closeness",
        "name": "INTIMACY IS CLOSENESS",
        "kind": "primary-metaphor",
        "source_frame": "embodied-experience",
        "target_frame": "love-and-relationships",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Grady 1997; Lakoff & Johnson 1999 pp. 50",
        "description": "Close relationships are 'close', estrangement is 'distance'. We 'grow apart' or 'come together'. The embodied correlation: physical proximity to caregivers correlates with emotional intimacy in infancy.",
    },
    {
        "slug": "difficulties-are-burdens",
        "name": "DIFFICULTIES ARE BURDENS",
        "kind": "primary-metaphor",
        "source_frame": "embodied-experience",
        "target_frame": "event-structure",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Grady 1997; Lakoff & Johnson 1999 pp. 52",
        "description": "Problems are 'heavy', we carry 'burdens', responsibilities 'weigh on' us. The embodied grounding: carrying heavy objects impedes movement and causes fatigue.",
    },
    {
        "slug": "time-is-motion",
        "name": "TIME IS MOTION",
        "kind": "primary-metaphor",
        "source_frame": "embodied-experience",
        "target_frame": "time-and-temporality",
        "categories": ["cognitive-science", "linguistics", "philosophy"],
        "source": "llm",
        "archive_ref": "Lakoff & Johnson 1999 pp. 52; also 'The Contemporary Theory of Metaphor' (Lakoff 1993)",
        "description": "The master time metaphor: temporal passage is spatial motion. Subsumes both 'moving time' (time comes toward us) and 'moving observer' (we move through time). Lakoff & Johnson argue this is a primary metaphor grounded in the correlation of experienced events with perceived motion.",
    },
    {
        "slug": "purposes-are-desired-objects",
        "name": "PURPOSES ARE DESIRED OBJECTS",
        "kind": "primary-metaphor",
        "source_frame": "embodied-experience",
        "target_frame": "event-structure",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Lakoff & Johnson 1999 pp. 53",
        "description": "Goals are things we 'pursue', 'reach for', 'get', 'obtain'. The embodied grounding: infants correlate achieving desired states with acquiring desired objects.",
    },
    {
        "slug": "actions-are-self-propelled-motions",
        "name": "ACTIONS ARE SELF-PROPELLED MOTIONS",
        "kind": "primary-metaphor",
        "source_frame": "embodied-experience",
        "target_frame": "event-structure",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Lakoff & Johnson 1999 pp. 52",
        "description": "Volitional action is self-propelled movement. We 'proceed', 'go ahead', 'move on' an initiative. The correlation: voluntary bodily motion is the prototype of intentional action.",
    },
    {
        "slug": "relationships-are-enclosures",
        "name": "RELATIONSHIPS ARE ENCLOSURES",
        "kind": "primary-metaphor",
        "source_frame": "containers",
        "target_frame": "love-and-relationships",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Lakoff & Johnson 1999 pp. 53",
        "description": "We are 'in' relationships, 'trapped' in marriages, 'get out of' friendships. The container image schema structures relational commitment.",
    },
    {
        "slug": "anger-is-a-heated-fluid-in-a-container",
        "name": "ANGER IS A HEATED FLUID IN A CONTAINER",
        "kind": "conceptual-metaphor",
        "source_frame": "fluid-dynamics",
        "target_frame": "mental-experience",
        "categories": ["cognitive-science", "linguistics", "psychology"],
        "source": "llm",
        "archive_ref": "Lakoff 1987 Case Study 1; Kovecses 1986; Lakoff & Kovecses 1987",
        "description": "The most thoroughly analyzed complex metaphor in cognitive linguistics. Anger is a hot fluid in the body-container: we 'boil over', 'let off steam', 'simmer'. The body is the container, anger is the fluid, its intensity is heat, loss of control is explosion. Composes ANGER IS HEAT + THE BODY IS A CONTAINER + EMOTIONS ARE FLUIDS.",
    },
    {
        "slug": "nation-is-a-person",
        "name": "NATION IS A PERSON",
        "kind": "conceptual-metaphor",
        "source_frame": "social-roles",
        "target_frame": "governance",
        "categories": ["cognitive-science", "linguistics", "philosophy"],
        "source": "llm",
        "archive_ref": "Lakoff 1996 'Moral Politics'; Lakoff 2002 'Moral Politics' 2nd ed.",
        "description": "Nations have 'interests', 'friends', 'enemies'. They can be 'healthy' or 'sick', 'young' or 'mature'. This personification metaphor structures international relations discourse and foreign policy reasoning.",
    },
    {
        "slug": "nation-is-a-family",
        "name": "NATION IS A FAMILY",
        "kind": "conceptual-metaphor",
        "source_frame": "social-roles",
        "target_frame": "governance",
        "categories": ["cognitive-science", "linguistics", "philosophy"],
        "source": "llm",
        "archive_ref": "Lakoff 1996 'Moral Politics' Ch 1-5",
        "description": "The government is a parent, citizens are children. Lakoff's central thesis in Moral Politics: conservative politics maps to the Strict Father model, progressive politics to the Nurturant Parent model. The family metaphor structures moral reasoning about governance.",
    },
    {
        "slug": "morality-is-accounting",
        "name": "MORALITY IS ACCOUNTING",
        "kind": "conceptual-metaphor",
        "source_frame": "economics",
        "target_frame": "ethics-and-morality",
        "categories": ["cognitive-science", "linguistics", "philosophy"],
        "source": "archive",
        "archive_ref": "Osaka archive: Moral_Accounting.html; Lakoff & Johnson 1999 Ch 15",
        "description": "Good deeds are credits, bad deeds are debts. We 'owe' people, 'repay' kindness, seek 'balance'. Revenge is 'getting even'. This metaphor structures retributive justice systems.",
    },
    {
        "slug": "death-is-departure",
        "name": "DEATH IS DEPARTURE",
        "kind": "conceptual-metaphor",
        "source_frame": "journeys",
        "target_frame": "life-course",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Lakoff & Turner 1989 'More Than Cool Reason' Ch 1",
        "description": "The dead have 'passed on', 'departed', 'gone'. Death is leaving on a journey. Lakoff and Turner analyze this as part of the LIFE IS A JOURNEY system, where death is the final destination or departure.",
    },
    {
        "slug": "life-is-a-story",
        "name": "LIFE IS A STORY",
        "kind": "conceptual-metaphor",
        "source_frame": "creative-process",
        "target_frame": "life-course",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Lakoff & Turner 1989; Turner 1996 'The Literary Mind'",
        "description": "Lives have 'chapters', 'turning points', 'plots'. We 'write' our own story. Turner argues narrative is a fundamental cognitive operation, not just a literary form.",
    },
    {
        "slug": "the-great-chain-of-being",
        "name": "THE GREAT CHAIN OF BEING",
        "kind": "conceptual-metaphor",
        "source_frame": "natural-selection",
        "target_frame": "social-roles",
        "categories": ["cognitive-science", "linguistics", "philosophy"],
        "source": "llm",
        "archive_ref": "Lakoff & Turner 1989 'More Than Cool Reason' Ch 4",
        "description": "A hierarchical ordering: God > humans > animals > plants > minerals. Each level has characteristic properties. Lakoff and Turner argue this folk model structures personification (attributing human properties down the chain) and dehumanization (attributing animal properties to humans).",
    },
    {
        "slug": "argument-is-a-container",
        "name": "ARGUMENT IS A CONTAINER",
        "kind": "conceptual-metaphor",
        "source_frame": "containers",
        "target_frame": "argumentation",
        "categories": ["cognitive-science", "linguistics"],
        "source": "llm",
        "archive_ref": "Lakoff & Johnson 1980 Ch 6",
        "description": "Arguments have 'content', can be 'full of holes' or 'empty'. You can 'pack' an argument with evidence. The container schema structures the experience of argument as a bounded entity that holds things.",
    },
]


def map_source_frame(stub: str) -> str:
    """Map an Osaka source stub to a frame slug."""
    key = stub.lower().strip()
    return FRAME_MAP.get(key, "embodied-experience")


def map_target_frame(stub: str) -> str:
    """Map an Osaka target stub to a frame slug."""
    key = stub.lower().strip()
    return TARGET_FRAME_MAP.get(key, "event-structure")


def classify_kind(name: str) -> str:
    """Assign a kind based on the metaphor name."""
    name_lower = name.lower()
    # Event structure system entries
    if "event structure" in name_lower:
        return "conceptual-metaphor"
    # Orientational metaphors
    if " is up" in name_lower or " is down" in name_lower:
        return "primary-metaphor"
    # Primary metaphors (simple, universal)
    primary_markers = [
        "is warmth", "is heat", "is cold", "is closeness",
        "is balance", "is motion", "is light", "is alive",
    ]
    for marker in primary_markers:
        if marker in name_lower:
            return "primary-metaphor"
    return "conceptual-metaphor"


def describe_candidate(name: str, source_stub: str, target_stub: str) -> str:
    """Generate a brief description for a candidate."""
    return (
        f"From the Master Metaphor List / Osaka archive. "
        f"Maps {source_stub} onto {target_stub}."
    )


def main():
    osaka_data = json.load(sys.stdin)

    candidates = []
    seen_slugs = set()

    # Process Osaka archive entries
    for entry in osaka_data:
        slug = entry["slug"]

        # Skip entries already in the catalog
        if slug in EXISTING_SLUGS:
            continue

        # Skip duplicates within this run
        if slug in seen_slugs:
            continue
        seen_slugs.add(slug)

        source_frame = map_source_frame(entry["source_stub"])
        target_frame = map_target_frame(entry["target_stub"])
        kind = classify_kind(entry["name"])

        candidates.append({
            "slug": slug,
            "name": entry["name"],
            "kind": kind,
            "source_frame": source_frame,
            "target_frame": target_frame,
            "categories": ["cognitive-science", "linguistics"],
            "source": "archive",
            "archive_ref": f"Osaka archive: {entry['filename']}; Master Metaphor List (Lakoff, Espenson & Schwartz 1991)",
            "description": describe_candidate(
                entry["name"], entry["source_stub"], entry["target_stub"]
            ),
        })

    # Add primary metaphors and notable complex metaphors not in Osaka
    for pm in ADDITIONAL_PRIMARY_METAPHORS:
        if pm["slug"] not in EXISTING_SLUGS and pm["slug"] not in seen_slugs:
            seen_slugs.add(pm["slug"])
            candidates.append(pm)

    # Build final manifest
    manifest = {
        "project": "cognitive-linguistics-canon",
        "project_issue": 4,
        "source_type": "vein",
        "archive_urls": [
            "http://www.lang.osaka-u.ac.jp/~sugimoto/MasterMetaphorList/metaphors/index.html",
            "http://www.lang.osaka-u.ac.jp/~sugimoto/MasterMetaphorList/sources/index.html",
            "http://www.lang.osaka-u.ac.jp/~sugimoto/MasterMetaphorList/targets/index.html",
            "http://araw.mede.uic.edu/~alansz/metaphor/METAPHORLIST.pdf",
            "https://metaphor.icsi.berkeley.edu/pub/en/index.php/MetaNet_Metaphor_Wiki",
        ],
        "candidates": candidates,
    }

    json.dump(manifest, sys.stdout, indent=2)
    print(file=sys.stdout)

    # Summary stats
    archive_count = sum(1 for c in candidates if c["source"] == "archive")
    llm_count = sum(1 for c in candidates if c["source"] == "llm")
    print(
        f"Total: {len(candidates)} candidates "
        f"({archive_count} archive, {llm_count} LLM-sourced)",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
